language: csharp
mono: none
dotnet: 2.0.0
script:
    - dotnet build -c Release
    - dotnet pack Amsterdam.Http.Extensions/Amsterdam.Http.Extensions.csproj -c Release --version-suffix "$TRAVIS_BUILD_ID"
