language: csharp
mono: none
dotnet: 2.1.301
script:
    - dotnet pack Amsterdam.Http.Extensions/Amsterdam.Http.Extensions.csproj -c Release /p:Version=1.0.$TRAVIS_BUILD_NUMBER -o ../output/nupkg/
    - dotnet nuget push output/nupkg/*.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json